// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RoutesHandlerFunc turns a function with the right signature into a routes handler
type RoutesHandlerFunc func(RoutesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RoutesHandlerFunc) Handle(params RoutesParams) middleware.Responder {
	return fn(params)
}

// RoutesHandler interface for that can handle valid routes params
type RoutesHandler interface {
	Handle(RoutesParams) middleware.Responder
}

// NewRoutes creates a new http.Handler for the routes operation
func NewRoutes(ctx *middleware.Context, handler RoutesHandler) *Routes {
	return &Routes{Context: ctx, Handler: handler}
}

/* Routes swagger:route GET /routes Routes routes

Routes routes API

*/
type Routes struct {
	Context *middleware.Context
	Handler RoutesHandler
}

func (o *Routes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRoutesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
