// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// RoutesURL generates an URL for the routes operation
type RoutesURL struct {
	Dst [][]string
	Src []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RoutesURL) WithBasePath(bp string) *RoutesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RoutesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *RoutesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/routes"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var dstIR []string
	for _, dstI := range o.Dst {
		var dstIIR []string
		for _, dstII := range dstI {
			dstIIS := dstII
			if dstIIS != "" {
				dstIIR = append(dstIIR, dstIIS)
			}
		}

		dstIS := swag.JoinByFormat(dstIIR, "csv")
		if len(dstIS) > 0 {
			dstISs := dstIS[0]
			if dstISs != "" {
				dstIR = append(dstIR, dstISs)
			}
		}
	}

	dst := swag.JoinByFormat(dstIR, "multi")

	for _, qsv := range dst {
		qs.Add("dst", qsv)
	}

	var srcIR []string
	for _, srcI := range o.Src {
		srcIS := srcI
		if srcIS != "" {
			srcIR = append(srcIR, srcIS)
		}
	}

	src := swag.JoinByFormat(srcIR, "csv")

	if len(src) > 0 {
		qsv := src[0]
		if qsv != "" {
			qs.Set("src", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *RoutesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *RoutesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *RoutesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on RoutesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on RoutesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *RoutesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
