version: '3.3'
services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      HTTP_LISTEN_HOST: ''
      HTTP_LISTEN_PORT: '8080'
      DEBUG_LISTEN: ':6060'
      VERBOSE: 'true'
    ports:
    - '8080:8080'
    - '6060:6060'